"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd party
    'rest_framework',
    'drf_spectacular',

    # custom
    'stations',
    'routing',
    'planner',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---- PROJECT CONFIGURATION ----
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "api.errors.api_exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Station - Fuel Route API",
    "DESCRIPTION": (
        "Give a start and finish inside the USA; get the driving route, the cheapest places to fuel up "
        "(500-mile range) and the total fuel cost at 10 MPG."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}


FUEL_CSV_PATH = BASE_DIR / "data" / "fuel-prices.csv"
GEOCODE_CACHE_PATH = BASE_DIR / "data" / "geocode_cache.json"
GEOCODER_USER_AGENT = "fuelroute-assessment/0.1 (contact: wisdomzino42@gmail.com)" # Nominatim's usage policy requires an identifying User-Agent.


# ---- Routing ----
# "osrm" needs no key (public demo server; fine for an assessment, self-host for production).
# "ors" = OpenRouteService; needs ORS_API_KEY (free tier).
ROUTING_PROVIDER = os.getenv("ROUTING_PROVIDER", "osrm")
OSRM_BASE_URL = os.getenv("OSRM_BASE_URL", "https://router.project-osrm.org")
ORS_BASE_URL = os.getenv("ORS_BASE_URL", "https://api.openrouteservice.org")
ORS_API_KEY = os.getenv("ORS_API_KEY", "")
ROUTING_TIMEOUT = 20      # seconds, directions call
GEOCODE_TIMEOUT = 8       # seconds, free-text location lookup
ROUTE_CACHE_SECONDS = 60 * 60 * 24

# Local-memory cache is per-process;
CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}

# ---- Trip planning ----
VEHICLE_RANGE_MILES = 500   # max distance on a full tank
VEHICLE_MPG = 10
# How far (straight-line miles) a station may sit from the route and still count.
# Stations are geocoded at city level, so this also absorbs that imprecision.
CORRIDOR_MILES = 10

# ---- Map tiles ----
# Django's default Referrer-Policy is "same-origin", which makes browsers drop the Referer header on
# cross-origin requests. OpenStreetMap's tile servers REQUIRE a Referer (their tile usage policy) and
# answer 403 "Access blocked" without one. Sending the origin on cross-origin requests fixes that.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# OSM's public tiles are fine for a demo/assessment (light use). If they ever block you, switch to
# another provider by changing these two settings, e.g. CARTO:
#   MAP_TILE_URL = "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png"
#   MAP_TILE_ATTRIBUTION = "&copy; OpenStreetMap contributors &copy; CARTO"
MAP_TILE_URL = "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
MAP_TILE_ATTRIBUTION = "&copy; OpenStreetMap contributors"
